\RequirePackage[utf8]{inputenc}
\RequirePackage[spanish]{babel}
\RequirePackage{graphicx}
\RequirePackage{anysize}
\RequirePackage{fancyhdr} % Para agregar encabezado y pie de página
\RequirePackage[hidelinks, colorlinks=true,linkcolor=black,urlcolor=blue]{hyperref}
\RequirePackage{float}
\RequirePackage{tabu}
\decimalpoint % Para que el 'punto' no se vea como 'coma'
\marginsize{2cm}{2cm}{2cm}{2.5cm} % Izquierda, derecha, arriba, abajo